//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CJ_sComics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comic
    {
        public System.Guid ComicBookId { get; set; }
        public string ComicTitle { get; set; }
        public string EpisodeNumber { get; set; }
        public string EpisodeTitle { get; set; }
        public string Characters { get; set; }
    }
}
